[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_CONVEX_URL = "your-convex-url-here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
